# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reward_pb2 as reward__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in reward_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RewardServiceStub(object):
    """Reward service for managing contributor tokens
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/cowcow.RewardService/GetBalance',
                request_serializer=reward__pb2.BalanceRequest.SerializeToString,
                response_deserializer=reward__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_stream(
                '/cowcow.RewardService/GetHistory',
                request_serializer=reward__pb2.HistoryRequest.SerializeToString,
                response_deserializer=reward__pb2.Transaction.FromString,
                _registered_method=True)


class RewardServiceServicer(object):
    """Reward service for managing contributor tokens
    """

    def GetBalance(self, request, context):
        """Get the current token balance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Get token transaction history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RewardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=reward__pb2.BalanceRequest.FromString,
                    response_serializer=reward__pb2.BalanceResponse.SerializeToString,
            ),
            'GetHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=reward__pb2.HistoryRequest.FromString,
                    response_serializer=reward__pb2.Transaction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cowcow.RewardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cowcow.RewardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RewardService(object):
    """Reward service for managing contributor tokens
    """

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cowcow.RewardService/GetBalance',
            reward__pb2.BalanceRequest.SerializeToString,
            reward__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cowcow.RewardService/GetHistory',
            reward__pb2.HistoryRequest.SerializeToString,
            reward__pb2.Transaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
