# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import upload_pb2 as upload__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in upload_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UploadServiceStub(object):
    """Upload service for sending recordings to the server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadChunk = channel.stream_unary(
                '/cowcow.UploadService/UploadChunk',
                request_serializer=upload__pb2.Chunk.SerializeToString,
                response_deserializer=upload__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.GetUploadStatus = channel.unary_unary(
                '/cowcow.UploadService/GetUploadStatus',
                request_serializer=upload__pb2.UploadRequest.SerializeToString,
                response_deserializer=upload__pb2.UploadStatus.FromString,
                _registered_method=True)


class UploadServiceServicer(object):
    """Upload service for sending recordings to the server
    """

    def UploadChunk(self, request_iterator, context):
        """Upload a recording in chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUploadStatus(self, request, context):
        """Get the status of an upload
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UploadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadChunk': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadChunk,
                    request_deserializer=upload__pb2.Chunk.FromString,
                    response_serializer=upload__pb2.UploadResponse.SerializeToString,
            ),
            'GetUploadStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUploadStatus,
                    request_deserializer=upload__pb2.UploadRequest.FromString,
                    response_serializer=upload__pb2.UploadStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cowcow.UploadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cowcow.UploadService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UploadService(object):
    """Upload service for sending recordings to the server
    """

    @staticmethod
    def UploadChunk(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/cowcow.UploadService/UploadChunk',
            upload__pb2.Chunk.SerializeToString,
            upload__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUploadStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cowcow.UploadService/GetUploadStatus',
            upload__pb2.UploadRequest.SerializeToString,
            upload__pb2.UploadStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
