# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: upload.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'upload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cupload.proto\x12\x06\x63owcow\"\x92\x01\n\x05\x43hunk\x12\x14\n\x0crecording_id\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12%\n\nqc_metrics\x18\x04 \x01(\x0b\x32\x11.cowcow.QcMetrics\x12\x0c\n\x04lang\x18\x05 \x01(\t\x12\x13\n\x06prompt\x18\x06 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_prompt\"D\n\tQcMetrics\x12\x0e\n\x06snr_db\x18\x01 \x01(\x02\x12\x14\n\x0c\x63lipping_pct\x18\x02 \x01(\x02\x12\x11\n\tvad_ratio\x18\x03 \x01(\x02\"W\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\x0etokens_awarded\x18\x03 \x01(\rB\x08\n\x06_error\"%\n\rUploadRequest\x12\x14\n\x0crecording_id\x18\x01 \x01(\t\"\xdb\x01\n\x0cUploadStatus\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.cowcow.UploadStatus.Status\x12\x10\n\x08progress\x18\x02 \x01(\r\x12\x12\n\x05\x65rror\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x17\n\x0f\x63hunks_uploaded\x18\x04 \x01(\r\x12\x14\n\x0ctotal_chunks\x18\x05 \x01(\r\"?\n\x06Status\x12\x0b\n\x07PENDING\x10\x00\x12\r\n\tUPLOADING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x42\x08\n\x06_error2\x87\x01\n\rUploadService\x12\x36\n\x0bUploadChunk\x12\r.cowcow.Chunk\x1a\x16.cowcow.UploadResponse(\x01\x12>\n\x0fGetUploadStatus\x12\x15.cowcow.UploadRequest\x1a\x14.cowcow.UploadStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNK']._serialized_start=25
  _globals['_CHUNK']._serialized_end=171
  _globals['_QCMETRICS']._serialized_start=173
  _globals['_QCMETRICS']._serialized_end=241
  _globals['_UPLOADRESPONSE']._serialized_start=243
  _globals['_UPLOADRESPONSE']._serialized_end=330
  _globals['_UPLOADREQUEST']._serialized_start=332
  _globals['_UPLOADREQUEST']._serialized_end=369
  _globals['_UPLOADSTATUS']._serialized_start=372
  _globals['_UPLOADSTATUS']._serialized_end=591
  _globals['_UPLOADSTATUS_STATUS']._serialized_start=518
  _globals['_UPLOADSTATUS_STATUS']._serialized_end=581
  _globals['_UPLOADSERVICE']._serialized_start=594
  _globals['_UPLOADSERVICE']._serialized_end=729
# @@protoc_insertion_point(module_scope)
